### ISSUE TITLE
Hivemanager Settings

### ISSUE THREAD

**Issue by Daryolo** [wagtail9019/Zabbix-Template#2]
Hello there

I wanted to implement this one in my zabbix monitoring server. But somehow the SNMP doesn't light up green. Can you tell me what you had to adjust in the hive manager? 
I tried a lot of things already, but yet it doesn't work.

And do you put the IP-address of the access point itself?

Greetings,
Daryolo

**Comment by bgp4plus** [comment]
Hi,
Is the SNMP community string correct?
Check Host-> Macro-> {$ SNMP_COMMUNITY}.
Thank,

**Comment by Daryolo** [comment]
Got it work, thank you! Something was wrong on the Hivemanager-side. It didn't save the snmp-server when I configured it via GUI. But over CLI it worked
