### ISSUE TITLE
Importing issue Zabbix 5.4.4

### ISSUE THREAD

**Issue by Lucienk94** [wagtail9019/Zabbix-Template#3]
The following is shown when trying to import the Aerohive AP.

"Cannot import template "Aerohive AP", linked templates "Template Module EtherLike-MIB SNMPv2, Template Module Generic SNMPv2, Template Module Interfaces SNMP" do not exist."

We are running Zabbix 5.4.4.

**Comment by bgp4plus** [comment]
Hi,

Template name seems to have changed in Zabbix 5.4.
https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/module?at=release/5.4

Make the following changes to Aerohive_AP.xml before importing.
```
<templates>
    <template>
        <name>EtherLike-MIB SNMP</name>
    </template>
    <template>
        <name>Generic SNMP</name>
    </template>
    <template>
        <name>Interfaces SNMP</name>
    </template>
</templates>
```
If it still doesn't work, change the name to your existing template name or remove the above tags.

Thanks,

**Comment by Lucienk94** [comment]
Thanks, it works like a charm now!
